### PR TITLE
Clutter

### LINKED ISSUE #45: (1) Clutter
## Description
`Level 1`
> scrolling is s o o o o much effort. move the zodiac table and skeleton gifs from the home page to the about page so you can click there instead of having scroll. this also means people can focus more on baby yoda.

### PR DESCRIPTION
**Pull request by shambhavir**
fixes #45

### CODE REVIEW

**Review by shambhavir — COMMENTED** [review]
In this change I added the gifs and table to the about page. I also removed the gifs and table from the home page.

**Comment by mjrb** [comment]
fixes #45

**Comment by mjrb** [comment]
oof, two of these prs actually conflicted with each other. we asked someone to add different content to the about page. could you potentially try to revert what was on the about page before and instead move this stuff to a new "fun facts" page? @shambhavir

**Comment by mjrb** [comment]
oh, i also merged in master so you should pull this branch when you work on it again

**Comment by shambhavir** [comment]
> oh, i also merged in master so you should pull this branch when you work on it again

**Comment by shambhavir** [comment]
> oof, two of these prs actually conflicted with each other. we asked someone to add different content to the about page. could you potentially try to revert what was on the about page before and instead move this stuff to a new "fun facts" page? @shambhavir

Yup, I can do that. Sorry about the issues.

**Pull request closed without merging**
