### PR TITLE
Fixed the Randomly colored button issue

### PR DESCRIPTION
**Pull request by sidselothcodes**
I have added a random color button on the home page, by creating a separate JSX file for that called RandomColorButton.jsx

### CODE REVIEW

**Review by sidselothcodes — COMMENTED** [review]
I have fixed the Movie page issue by embedding a YouTube video to it.

**Review by sidselothcodes — COMMENTED** [review]
I have made changes and added a randomly color generating button, let me know if it works.

**Comment by bhivam** [comment]
Please remove the .DS_Store file and then make a commit reflecting its deletion. It is causing a merge conflict.

**Comment by sidselothcodes** [comment]
I have deleted the .DS_Store file, I believe it should merge now.

**Pull request merged**
