### PR TITLE
Chatbox draggable in contact us page

### LINKED ISSUE #101: (3) Draggable Chat Window
## Description
`Level 3`
> `Contact Us` page has a 'reactment help' box. Make it draggable!

### PR DESCRIPTION
**Pull request by tang-michael**

### CODE REVIEW

**Review by lucentfong — DISMISSED** [review]
Hi, for the most part the code is good! The chatbox is indeed draggable now, however there is some weird behavior when I drag too quickly (when the mouse cursor goes past the chatbox itself, but I haven't let go of the mouse click). See if you can play around with how you handle the drag to resolve this (If you can't, don't worry too much. As always, feel free to email us if you have any questions)

**Comment by shivanmodha** [comment]
@tang-michael any updates on this?

**Comment by tang-michael** [comment]
@shivanmodha Hi, I just fixed the bug. Sorry for the delay!

**Review by shivanmodha — APPROVED** [review]
@tang-michael this looks great!

**Pull request merged**
